version: '3'

networks:
  webapp:

services:
  web:
    image: nginx:stable-alpine
    ports:
    - "${WEB_PORT}:80"
    links:
      - php
    env_file:
     - ./www/env
    volumes:
      - ./www:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
      - ./docker/logs/nginx:/var/logs/nginx:rw
    depends_on:
      - php
      - db
    networks:
      - webapp
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    env_file:
     - ./www/env
    volumes:
      - ./:/var/www/html
    networks:
      - webapp

  db:
    image: mariadb:10.6.4-focal
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - ./docker/mariadb:/var/lib/mysql 
    env_file:
     - ./www/env
    environment:
      MARIDB_USER: ${DB_USERNAME}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_DB: ${DB_DATABASE}
    networks:
      - webapp
phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}